In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
data = pd.read_csv("2020-12-31-DynamicallyGeneratedHateDataset-entries-v0.1.csv")

In [6]:
data.head()

,Unnamed: 0,id,text,label,type,model_wrong,db.model_preds,status,round,split,annotator
0,1,10000,It should be legal for a husband to rape his wife,hate,notgiven,True,0.97457,dynabench entry,1,train,gnzuctwed3
1,2,10001,dalits are lowlife scum,hate,notgiven,False,0.08233,dynabench entry,1,test,cagnluiznm
2,3,10002,dalits are lowlives,hate,notgiven,True,0.92319,dynabench entry,1,train,cagnluiznm
3,4,10003,It was a better world when women dare not ques...,hate,notgiven,True,0.99006,dynabench entry,1,test,gnzuctwed3
4,5,10004,I don't work this hard so that those immigrant...,hate,notgiven,True,0.98836,dynabench entry,1,train,cagnluiznm

In [7]:
data.info

<bound method DataFrame.info of        Unnamed: 0     id                                               text  \
0               1  10000  It should be legal for a husband to rape his wife
1               2  10001                            dalits are lowlife scum
2               3  10002                                dalits are lowlives
3               4  10003  It was a better world when women dare not ques...
4               5  10004  I don't work this hard so that those immigrant...
...           ...    ...                                                ...
40618       40736   9995  we should forcibly remove all the foreigners f...
40619       40737   9996  we should forcibly remove all the immigrants f...
40620       40738   9997               dalits are unworthy of the Gods love
40621       40739   9998                               dalits are worthless
40622       40740   9999       dalits are deserves to be treated as lowlife

      label      type model_wrong  db.model_preds           status round  \
0      hate  notgiven        True         0.97457  dynabench entry     1
1      hate  notgiven       False         0.08233  dynabench entry     1
2      hate  notgiven        True         0.92319  dynabench entry     1
3      hate  notgiven        True         0.99006  dynabench entry     1
4      hate  notgiven        True         0.98836  dynabench entry     1
...     ...       ...         ...             ...              ...   ...
40618  hate  notgiven        True         0.86945  dynabench entry     1
40619  hate  notgiven        True         0.50039  dynabench entry     1
40620  hate  notgiven        True         0.97652  dynabench entry     1
40621  hate  notgiven        True         0.94326  dynabench entry     1
40622  hate  notgiven        True         0.94324  dynabench entry     1

       split   annotator
0      train  gnzuctwed3
1       test  cagnluiznm
2      train  cagnluiznm
3       test  gnzuctwed3
4      train  cagnluiznm
...      ...         ...
40618  train  cagnluiznm
40619  train  cagnluiznm
40620  train  cagnluiznm
40621  train  cagnluiznm
40622  train  cagnluiznm

[40623 rows x 11 columns]>

In [8]:
data.shape

(40623, 11)

In [9]:
data.describe(include='all')

,Unnamed: 0,id,text,label,type,model_wrong,db.model_preds,status,round,split,annotator
count,40623.000000,40623,40623,40623,40623,26097,26097.000000,40623,40623,40623,40623
unique,NaN,40623,40463,2,7,2,NaN,2,5,3,20
top,NaN,10000,Blacks are such pondlife,hate,none,True,NaN,dynabench entry,1,train,gnzuctwed3
freq,NaN,1,6,22124,18499,15436,NaN,26097,11542,32497,6733
mean,20371.983236,NaN,NaN,NaN,NaN,NaN,0.585455,NaN,NaN,NaN,NaN
std,11743.590183,NaN,NaN,NaN,NaN,NaN,0.448801,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,0.000010,NaN,NaN,NaN,NaN
25%,10206.500000,NaN,NaN,NaN,NaN,NaN,0.036560,NaN,NaN,NaN,NaN
50%,20374.000000,NaN,NaN,NaN,NaN,NaN,0.910290,NaN,NaN,NaN,NaN
75%,30534.500000,NaN,NaN,NaN,NaN,NaN,0.995500,NaN,NaN,NaN,NaN
max,40740.000000,NaN,NaN,NaN,NaN,NaN,0.999920,NaN,NaN,NaN,NaN

In [10]:
data.columns

Index(['Unnamed: 0', 'id', 'text', 'label', 'type', 'model_wrong',
       'db.model_preds', 'status', 'round', 'split', 'annotator'],
      dtype='object')

In [11]:
# from pandas_profiling import ProfileReport
# profile = ProfileReport(data)
# profile.to_file('EDA.html')

In [12]:
# # importing sweetviz
# import sweetviz as sv
# #analyzing the dataset
# advert_report = sv.analyze(data)
# #display the report
# advert_report.show_html('auto_eda.html')

In [13]:
data.head(10)

,Unnamed: 0,id,text,label,type,model_wrong,db.model_preds,status,round,split,annotator
0,1,10000,It should be legal for a husband to rape his wife,hate,notgiven,True,0.97457,dynabench entry,1,train,gnzuctwed3
1,2,10001,dalits are lowlife scum,hate,notgiven,False,0.08233,dynabench entry,1,test,cagnluiznm
2,3,10002,dalits are lowlives,hate,notgiven,True,0.92319,dynabench entry,1,train,cagnluiznm
3,4,10003,It was a better world when women dare not ques...,hate,notgiven,True,0.99006,dynabench entry,1,test,gnzuctwed3
4,5,10004,I don't work this hard so that those immigrant...,hate,notgiven,True,0.98836,dynabench entry,1,train,cagnluiznm
5,6,10005,I don't work this hard so that those migrants ...,hate,notgiven,True,0.99506,dynabench entry,1,train,cagnluiznm
6,7,10006,I don't work this hard so that those foreigner...,hate,notgiven,True,0.99340,dynabench entry,1,train,cagnluiznm
7,8,10007,I don't work this hard so that those Hispanics...,hate,notgiven,True,0.98625,dynabench entry,1,train,cagnluiznm
8,9,10008,I don't work this hard so that those chavs can...,hate,notgiven,True,0.95252,dynabench entry,1,test,cagnluiznm
9,10,10009,I don't work this hard so that all those pakis...,hate,notgiven,False,0.09288,dynabench entry,1,train,cagnluiznm

In [14]:
data = data[['text', 'label']]

In [15]:
data.head()

                                                text label
0  It should be legal for a husband to rape his wife  hate
1                            dalits are lowlife scum  hate
2                                dalits are lowlives  hate
3  It was a better world when women dare not ques...  hate
4  I don't work this hard so that those immigrant...  hate

In [16]:
le = LabelEncoder()
data['label'] = le.fit_transform(data['label'])

C:\Users\0420\AppData\Local\Temp\ipykernel_12256\2814021135.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['label'] = le.fit_transform(data['label'])

In [17]:
data.label.value_counts()

label
0    22124
1    18499
Name: count, dtype: int64

In [18]:
def text_clean(text): 
    # changing to lower case
    lower = text.str.lower()
    
    # Replacing the repeating pattern of &#039;
    pattern_remove = lower.str.replace("&#039;", "")
    
    # Removing all the special Characters
    special_remove = pattern_remove.str.replace(r'[^\w\d\s]',' ')
    
    # Removing all the non ASCII characters
    ascii_remove = special_remove.str.replace(r'[^\x00-\x7F]+',' ')
    
    # Removing the leading and trailing Whitespaces
    whitespace_remove = ascii_remove.str.replace(r'^\s+|\s+?$','')
    
    # Replacing multiple Spaces with Single Space
    multiw_remove = whitespace_remove.str.replace(r'\s+',' ')
    
    # Replacing Two or more dots with one
    dataframe = multiw_remove.str.replace(r'\.{2,}', ' ')
    
    return dataframe

In [19]:
data['text_clean'] = text_clean(data['text'])

C:\Users\0420\AppData\Local\Temp\ipykernel_12256\2066393746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['text_clean'] = text_clean(data['text'])

In [20]:
data.head()

,text,label,text_clean
0,It should be legal for a husband to rape his wife,0,it should be legal for a husband to rape his wife
1,dalits are lowlife scum,0,dalits are lowlife scum
2,dalits are lowlives,0,dalits are lowlives
3,It was a better world when women dare not ques...,0,it was a better world when women dare not ques...
4,I don't work this hard so that those immigrant...,0,i don't work this hard so that those immigrant...

In [21]:
x = data['text_clean']
y= data['label']

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y, stratify=y, test_size=0.3, random_state=42)

In [23]:
# describes info about train and test set
print("Number transactions X_train dataset: ", x_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", x_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

Number transactions X_train dataset:  (28436,)
Number transactions y_train dataset:  (28436,)
Number transactions X_test dataset:  (12187,)
Number transactions y_test dataset:  (12187,)

In [24]:
from sklearn.feature_extraction.text import HashingVectorizer
hvectorizer = HashingVectorizer(n_features=10000,norm=None,alternate_sign=False,stop_words='english') 
x_train = hvectorizer.fit_transform(x_train).toarray()
x_test = hvectorizer.transform(x_test).toarray()

In [25]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
y_train.shape

TensorShape([28436])

In [28]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
# training the model
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
acc_lr = accuracy_score(y_test,y_pred)

print('The accuracy obtained by the Logistic Regression is: ',acc_lr)

C:\Users\0420\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

The accuracy obtained by the Logistic Regression is:  0.7039468285878395

In [29]:
result = lr.predict(hvectorizer.transform(['''Women are so oversensitive''']))
if result==0:
    print("The Entered Text is Detected as Hate Speech")
else:
    print("The Entered Text is Detected as NO-Hate Speech")

The Entered Text is Detected as Hate Speech

In [30]:
result = lr.predict(hvectorizer.transform(['''my meal was fucking disgusting''']))
if result==0:
    print("The Entered Text is Detected as Hate Speech")
else:
    print("The Entered Text is Detected as No-Hate Speech")

The Entered Text is Detected as No-Hate Speech

In [28]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt = dt.fit(x_train,y_train)
y_pred = dt.predict(x_test)
acc  = accuracy_score(y_test,y_pred)
acc

In [ ]:
result = dt.predict(hvectorizer.transform(['''who ever will oppose me i will kill them ''']))
if result==0:
    print("The Entered Text is Detected as Hate Speech")
else:
    print("The Entered Text is Detected as No-Hate Speech")

The Entered Text is Detected as No-Hate Speech

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb = nb.fit(x_train,y_train)
y_pred = nb.predict(x_test)
acc  = accuracy_score(y_test,y_pred)
acc

0.6503651431853614

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier()
adb = adb.fit(x_train,y_train)
y_pred = adb.predict(x_test)
acc  = accuracy_score(y_test,y_pred)
acc

0.6239435464019036

CNN

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf

In [32]:
x_train = tf.convert_to_tensor(x_train, dtype=tf.float32)
y_train = tf.convert_to_tensor(y_train, dtype=tf.float32)

In [33]:
x_test = tf.convert_to_tensor(x_test, dtype=tf.float32)
y_test = tf.convert_to_tensor(y_test, dtype=tf.float32)

In [34]:
model = Sequential()
model.add(Dense(30, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(1, activation='softmax'))

In [35]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [36]:
model.fit(x_train, y_train, batch_size=500, epochs=10,validation_data=(x_test, y_test))

Epoch 1/10
57/57 [==============================] - 2s 22ms/step - loss: 0.6750 - accuracy: 0.4554 - val_loss: 0.6464 - val_accuracy: 0.4554
Epoch 2/10
57/57 [==============================] - 1s 19ms/step - loss: 0.5883 - accuracy: 0.4554 - val_loss: 0.6059 - val_accuracy: 0.4554
Epoch 3/10
57/57 [==============================] - 1s 18ms/step - loss: 0.4965 - accuracy: 0.4554 - val_loss: 0.6036 - val_accuracy: 0.4554
Epoch 4/10
57/57 [==============================] - 1s 18ms/step - loss: 0.4309 - accuracy: 0.4554 - val_loss: 0.6277 - val_accuracy: 0.4554
Epoch 5/10
57/57 [==============================] - 1s 18ms/step - loss: 0.3808 - accuracy: 0.4554 - val_loss: 0.6615 - val_accuracy: 0.4554
Epoch 6/10
57/57 [==============================] - 1s 20ms/step - loss: 0.3372 - accuracy: 0.4554 - val_loss: 0.7079 - val_accuracy: 0.4554
Epoch 7/10
57/57 [==============================] - 1s 18ms/step - loss: 0.2997 - accuracy: 0.4554 - val_loss: 0.7538 - val_accuracy: 0.4554
Epoch 8/10
57/57 [==============================] - 1s 18ms/step - loss: 0.2681 - accuracy: 0.4554 - val_loss: 0.8065 - val_accuracy: 0.4554
Epoch 9/10
57/57 [==============================] - 1s 20ms/step - loss: 0.2374 - accuracy: 0.4554 - val_loss: 0.8643 - val_accuracy: 0.4554
Epoch 10/10
57/57 [==============================] - 1s 17ms/step - loss: 0.2086 - accuracy: 0.4554 - val_loss: 0.9329 - val_accuracy: 0.4554

In [37]:
abc=model.predict(x_test)

381/381 [==============================] - 1s 2ms/step

In [38]:
acc =accuracy_score(abc,y_test)

In [39]:
acc

0.4554032985968655

BERT

In [40]:
# split the data into train and test sets
train, test = train_test_split(data[:1000], test_size=0.3, random_state=42)

In [41]:
train.shape, test.shape

((700, 3), (300, 3))

In [43]:
train['label'].value_counts()

label
0    433
1    267
Name: count, dtype: int64

In [45]:
test['label'].value_counts()

label
0    196
1    104
Name: count, dtype: int64

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40623 entries, 0 to 40622
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   text        40623 non-null  object
 1   label       40623 non-null  int32
 2   text_clean  40623 non-null  object
dtypes: int32(1), object(2)
memory usage: 793.5+ KB

In [63]:
X_train = train.text_clean.tolist()
X_test = test.text_clean.tolist()

y_train = train['label'].tolist()
y_test = test['label'].tolist()

# Concatenate train and test DataFrames to create 'data'
data = pd.concat([train, test], ignore_index=True)

class_names = ['Hate Speech', 'Not Hate Speech']

print('Size of training set: %s' % len(train['text_clean']))
print('Size of validation set: %s' % len(test['text_clean']))
print(data['label'].value_counts())

data.head(10)

Size of training set: 700
Size of validation set: 300
label
0    629
1    371
Name: count, dtype: int64

,text,label,text_clean
0,Blacks are such pondlife,0,blacks are such pondlife
1,this government is full of junk,1,this government is full of junk
2,Mexicans are leeches,0,mexicans are leeches
3,black people shouldn't be allowed to exist,0,black people shouldn't be allowed to exist
4,brown people are the shit,1,brown people are the shit
5,White purity is under threat from Indians and ...,0,white purity is under threat from indians and ...
6,spinster women are abnormal,0,spinster women are abnormal
7,Blacks are inbred,0,blacks are inbred
8,Genocide of Indians is fine,0,genocide of indians is fine
9,i love men who hate women,1,i love men who hate women

In [64]:
# !pip install ktrain

In [65]:
import ktrain
from ktrain import text

In [66]:
(x_train,  y_train), (x_test, y_test), preproc = text.texts_from_array(x_train=X_train, y_train=y_train,
                                                                       x_test=X_test, y_test=y_test,
                                                                       class_names=class_names,
                                                                       preprocess_mode='bert',
                                                                       maxlen=350,
                                                                       max_features=35000)

preprocessing train...
language: en

Is Multi-Label? False
preprocessing test...
language: en

task: text classification

In [67]:
model = text.text_classifier('bert', train_data=(x_train, y_train), preproc=preproc)

Is Multi-Label? False
maxlen is 350

C:\Users\0420\AppData\Roaming\Python\Python310\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer GlorotNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(

done.

In [60]:
learner = ktrain.get_learner(model, train_data=(x_train, y_train),
                             val_data=(x_test, y_test),
                             batch_size=6)

In [61]:
learner.fit_onecycle(2e-5, 2)

begin training using onecycle policy with max lr of 2e-05...
Epoch 1/2
117/117 [==============================] - 1363s 11s/step - loss: 0.5262 - accuracy: 0.7414 - val_loss: 0.3279 - val_accuracy: 0.8667
Epoch 2/2
117/117 [==============================] - 1288s 11s/step - loss: 0.1828 - accuracy: 0.9300 - val_loss: 0.2695 - val_accuracy: 0.8800

In [68]:
learner.validate(val_data=(x_test, y_test), class_names=class_names)

10/10 [==============================] - 144s 14s/step
                 precision    recall  f1-score   support

    Hate Speech       0.90      0.92      0.91       196
Not Hate Speech       0.84      0.81      0.82       104

       accuracy                           0.88       300
      macro avg       0.87      0.86      0.87       300
   weighted avg       0.88      0.88      0.88       300

array([[180,  16],
       [ 20,  84]], dtype=int64)

In [69]:
predictor = ktrain.get_predictor(learner.model, preproc)
predictor.get_classes()

['Hate Speech', 'Not Hate Speech']

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   text        1000 non-null   object
 1   label       1000 non-null   int32
 2   text_clean  1000 non-null   object
dtypes: int32(1), object(2)
memory usage: 19.7+ KB

In [71]:
import pickle
# save
with open('BERT.pkl','wb') as f:
    pickle.dump(predictor,f)

In [72]:
predictor.save('bert_h5')

C:\Users\0420\AppData\Roaming\Python\Python310\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(